version: '3.8'

services:
  fastcep:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastcep-app
    env_file:
      - .env
    ports:
      - "8009:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fastcep-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_cep
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - fastcep-network
volumes:
  postgres_data:

networks:
  fastcep-network:
    name: fastcep-network
    driver: bridge